'use strict';
const fs=require('fs'); const path=require('path'); const assert=require('assert');
const root=path.resolve(__dirname,'..');
const read=(p)=>fs.readFileSync(path.join(root,p),'utf8');
const app=read('pos/app.js'); const cfg=read('configuracion/script.js'); const cfgHtml=read('configuracion/index.html'); const html=read('pos/index.html'); const sw=read('pos/sw.js'); const release=read('assets/js/a33-release.js'); const build=read('assets/js/a33-build.js'); const manifest=JSON.parse(read('pos/manifest.webmanifest'));
const has=(t,n,m)=>assert.ok(t.includes(n),m||`Falta ${n}`); const lacks=(t,n,m)=>assert.ok(!t.includes(n),m||`Sobra ${n}`);
has(app,'normalizeLotesStoragePayloadPOS','Falta normalización de contenedores históricos.');
has(app,"'records','items','entries','lotes','lots','archived'",'Faltan contenedores compatibles.');
has(app,'source.originalId','Falta originalId.');
has(app,'lotesReadProductRowsFromHistoricalLotPOS','Falta lectura de productos históricos.');
has(app,'lotesReadDynamicQuantityRowsPOS','Faltan Letras dinámicas históricas.');
has(app,'IDs de carga distintos representan cargas distintas','La deduplicación no respeta la prioridad de loteCargaId.');
has(app,"readPosStoresFreshPOS(['inventory','products','events','meta'])",'Falta lectura fresca integral.');
has(app,"readLotesStorageKeyPOS('arcano33_lotes_archived')",'Falta fuente archivada.');
lacks(app,"source:'reempaque'",'El puente no debe crear fuentes de Reempaque.');
has(cfg,'validatePosHistoricalImportContractReadback','Falta readback POS final.');
has(cfg,'A33_IMPORT_POS_READBACK_FAILED','Falta bloqueo de éxito parcial.');
has(cfg,'posContract:posContractReadback','Falta evidencia del contrato POS.'); has(cfgHtml,'a33-release.js?v=4.20.99&amp;r=61'); has(cfgHtml,'script.js?v=4.20.99&amp;r=36');
has(cfg,'registerBackupImport(file.name, obj, kind, result)','Falta registro posterior al éxito.');
assert.ok(cfg.indexOf('const result = await performImport(obj);') < cfg.indexOf('registerBackupImport(file.name, obj, kind, result)'), 'Se registra antes de validar.');
has(release,'const rev = 2;'); has(build,"pos:'51'"); has(html,'lotes-historico-pwa-hardening-final-r2-m51'); has(html,'app.js?v=4.20.99&r=47'); has(html,'manifest.webmanifest?v=4.20.99&r=28'); has(html,'a33-release.js?v=4.20.99&r=61'); has(html,"const REV = (window.A33_ASSET_REV || '2').toString();"); has(sw,"MODULE_CACHE_REV = '51'"); has(sw,'index.html?v=4.20.99&r=35'); has(sw,'app.js?v=4.20.99&r=47'); has(sw,'manifest.webmanifest?v=4.20.99&r=28'); assert.strictEqual(manifest.start_url,'./index.html?v=4.20.99&r=35');
lacks(sw,'m50'); lacks(html,'m50'); lacks(sw,'4.20.97');
console.log('SMOKE OK — Suite A33 POS Lotes cargados Etapa 2/2 Histórico + PWA hardening final');
