'use strict';
const fs = require('fs');
const path = require('path');
const assert = require('assert');
const root = path.resolve(__dirname, '..');
const read = (rel) => fs.readFileSync(path.join(root, rel), 'utf8');
const html = read('pos/index.html');
const js = read('pos/app.js');
const sw = read('pos/sw.js');
const build = read('assets/js/a33-build.js');
const release = read('assets/js/a33-release.js');
const manifest = JSON.parse(read('pos/manifest.webmanifest'));
const ok = (v,m)=>assert.ok(v,m);

ok(html.includes('meta name="a33-pos-shell" content="lotes-dinamicos-r5-m47"'), 'Falta marcador de shell POS');
ok(html.includes('app.js?v=4.20.97&r=43'), 'HTML no carga app corregida');
ok(html.includes('manifest.webmanifest?v=4.20.97&r=25'), 'HTML no carga manifest corregido');
ok(html.includes('a33-release.js?v=4.20.97&r=57'), 'HTML no fuerza release actual');
ok(html.includes('a33-build.js?v=4.20.97&r=15'), 'HTML no fuerza build actual');
ok(html.includes("&m=47"), 'Registro SW no incluye revisión modular');
ok(html.includes("updateViaCache: 'none'"), 'Registro SW puede reutilizar script viejo');
ok(sw.includes("const MODULE_CACHE_REV = '47';"), 'SW POS no avanzó a m47');
ok(sw.includes("new Request(request, { cache:'no-store' })"), 'Navegación no evita HTTP cache viejo');
ok(sw.indexOf("cache.match('./index.html?v=4.20.97&r=31')") < sw.indexOf('cache.match(request)'), 'Fallback offline no prioriza shell canónico');
ok(manifest.start_url === './index.html?v=4.20.97&r=31', 'Manifest no apunta al shell final');
ok(release.includes('const rev = 5;'), 'Release no avanzó a r5');
ok(build.includes("pos:'47'"), 'a33-build no coincide con m47');
ok(build.includes('global.A33_RELEASE'), 'a33-build no usa release como fuente');
ok(js.includes('function ensureLotesEventoShellPOS(){'), 'Falta recuperación de shell mixto');
ok(js.includes('data-a33-shell-recovered="1"'), 'Recuperación no marca el bloque reconstruido');
ok(js.includes('try{ ensureLotesEventoShellPOS(); }catch(err)'), 'Init no recupera shell antes de datos');
ok(js.includes('function bindLotesEventoToggleOncePOS(){\n  ensureLotesEventoShellPOS();'), 'Binding no recupera shell antes de enlazar');
ok(!js.includes('localStorage.clear('), 'La reparación borra localStorage');
ok(!js.includes('indexedDB.deleteDatabase('), 'La reparación borra IndexedDB');
console.log('SMOKE OK — POS Lotes cargados shell/cache fix r5 m47');
