const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const root = path.resolve(__dirname, '..');
const source = fs.readFileSync(path.join(root, 'assets/js/a33-firebase-users-connect-e94a.js'), 'utf8');
const accessSource = fs.readFileSync(path.join(root, 'assets/js/a33-firebase-access.js'), 'utf8');
const html = fs.readFileSync(path.join(root, 'configuracion/index.html'), 'utf8');
const script = fs.readFileSync(path.join(root, 'configuracion/script.js'), 'utf8');
const sandbox = { globalThis:null };
sandbox.globalThis = sandbox;
vm.runInNewContext(source, sandbox);
const base = { user:{uid:'master'}, profile:{status:'active'}, role:'admin', isAdmin:true, workspaceId:'arcano33', backendMode:'functions' };
const pending = sandbox.A33UsersConnectE94A.validate({...base, backendHealth:'missing', managementReady:false});
assert.equal(pending.connectorPrepared, true);
assert.equal(pending.safeFallback, true);
assert.equal(pending.administrationEnabled, false);
const ready = sandbox.A33UsersConnectE94A.validate({...base, backendHealth:'ready', managementReady:true});
assert.equal(ready.connectorPrepared, true);
assert.equal(ready.administrationEnabled, true);
const unsafe = sandbox.A33UsersConnectE94A.validate({...base, backendHealth:'error', managementReady:true});
assert.equal(unsafe.connectorPrepared, false);
assert(accessSource.includes("const BACKEND_MODE = 'functions'"));
assert(accessSource.includes("call('a33AdminHealthcheck'"));
assert(accessSource.includes("claims.workspaceId === ws && claims.role === 'admin' && claims.status === 'active'"));
assert(html.includes('id="cfg-security-e94a-run"'));
assert(html.includes('a33-firebase-users-connect-e94a.js?v=4.20.98&amp;r=1'));
assert(script.includes('function initUsersConnectE94A()'));
assert(script.includes("window.A33Toast.warning('E9.4A confirmada: Functions pendiente y administración real apagada.')"));
assert(script.includes("window.A33Toast.success('E9.4A confirmada: backend administrativo disponible.')"));
console.log('OK a33-firebase-users-etapa9-4a.smoke');
