'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const source=fs.readFileSync(path.join(__dirname,'../configuracion/script.js'),'utf8');
const region=source.slice(source.indexOf('  const PWA_KEYS'),source.indexOf('  function reqToPromise'));
function worker(state='installed',outcome='activated'){
 const events=new Map();return {state,scriptURL:'https://suite.test/pos/sw.js',addEventListener(t,f){events.set(t,f);},removeEventListener(t){events.delete(t);},postMessage(){this.state=outcome;events.get('statechange')?.();}};
}
function registration(id,w=null){
 if(w)w.scriptURL=`https://suite.test/${id}/sw.js`;
 return {scope:`https://suite.test/${id}/`,waiting:w,active:Object.assign(worker('activated'),{scriptURL:`https://suite.test/${id}/sw.js`}),installing:null,async update(){},addEventListener(){},removeEventListener(){}};
}
function harness(regs, failMissing=false){
 const registered=[];
 const data=new Map(),items=[];const button={textContent:'',setAttribute(){},addEventListener(){},classList:{toggle(){}}};
 const applyButton={...button};
 const document={addEventListener(){},getElementById(id){if(id==='cfg-pwa-report')return {replaceChildren(){items.length=0;},appendChild(item){items.push(item.textContent);}};if(id==='cfg-pwa-check')return button;if(id==='cfg-pwa-apply')return applyButton;return null;},querySelector(){return null;},createElement(){return {textContent:''};}};
 const window={addEventListener(){},location:{href:'https://suite.test/configuracion/index.html',origin:'https://suite.test'},confirm(){return true;},A33Notice:{show(){}}};
 const context=vm.createContext({window,document,navigator:{serviceWorker:{async getRegistrations(){return regs;},async register(url,options){registered.push({url,options});if(failMissing)throw new Error('sin conexión');const id=new URL(options.scope).pathname.split('/').filter(Boolean).pop();const reg=registration(id);regs.push(reg);return reg;}}},localStorage:{getItem:k=>data.get(k)||null,setItem:(k,v)=>data.set(k,v)},sessionStorage:{getItem(){},setItem(){}},URL,Date,JSON,Set,Promise,showToast(){},setTimeout:(f,ms)=>setTimeout(f,Math.min(ms,20)),clearTimeout,setInterval:f=>setInterval(f,1),clearInterval});
 vm.runInContext(region+'\n;globalThis.api={checkSuitePwaUpdates,applySuitePwaUpdate,handlePwaCheck,handlePwaApply,waitForPwaRegistrationActivation,inspectPwaRegistration,initPwaSection,renderPwaSection,pwaRuntime,PWA_STATUS,PWA_KEYS,getSuitePwaRegistrations,reconcilePwaState,observePwaActivation};',context);
 return {api:context.api,data,items,button,applyButton,registered};
}
(async()=>{
 let h=harness([]);await h.api.handlePwaCheck();assert.equal(h.data.get(h.api.PWA_KEYS.status),h.api.PWA_STATUS.current);assert.equal(h.registered.length,11);assert.equal(h.items.length,11);assert.equal(h.applyButton.disabled,true);
 const unknown=registration('desconocido');h=harness([registration('pos'),unknown,registration('centro_mando')]);assert.equal((await h.api.getSuitePwaRegistrations()).length,1);await h.api.handlePwaCheck();assert.equal(h.data.get(h.api.PWA_KEYS.status),h.api.PWA_STATUS.current);assert.equal(h.registered.length,10);assert(h.items.some(x=>x.startsWith('POS: Sin actualización')));
 const ids=['pos','inventario','lotes','pedidos','catalogos','calculadora','agenda','centro-mando','calculadora_temporal','finanzas','analitica'];
 h=harness(ids.map(id=>registration(id)));await h.api.handlePwaCheck();assert.equal(h.data.get(h.api.PWA_KEYS.status),h.api.PWA_STATUS.current);assert.equal(h.applyButton.disabled,true);
 const broken=registration('pos');broken.update=async()=>{throw new Error('sin conexión');};h=harness([broken,registration('pedidos',worker())]);await h.api.handlePwaCheck();assert.equal(h.data.get(h.api.PWA_KEYS.status),h.api.PWA_STATUS.partialSearch);assert.equal(h.button.textContent,'Buscar actualizaciones');assert.equal(h.applyButton.textContent,'Actualizar Suite');assert.equal(h.applyButton.disabled,false);assert(h.items.some(x=>x.includes('sin conexión')));h.api.pwaRuntime.updateAvailable=false;await h.api.initPwaSection();assert.equal(h.button.textContent,'Buscar actualizaciones');assert.equal(h.applyButton.textContent,'Actualizar Suite');assert.equal(h.applyButton.disabled,false);
 const installing=registration('pos');installing.installing=worker('installing');h=harness([installing]);const summary=await h.api.checkSuitePwaUpdates();assert.equal(summary.available,false);assert.equal(summary.results[0].status,'installing');
 installing.installing.state='redundant';assert.equal((await h.api.inspectPwaRegistration(installing)).status,'error');
 h=harness([registration('pos',worker()),registration('pedidos',worker('installed','redundant'))]);h.data.set(h.api.PWA_KEYS.lastUpdate,'histórico');await h.api.handlePwaApply();assert.equal(h.data.get(h.api.PWA_KEYS.status),h.api.PWA_STATUS.partialApply);assert.equal(h.data.get(h.api.PWA_KEYS.lastUpdate),'histórico');assert(h.items.some(x=>x.startsWith('POS: Activación confirmada')));assert(h.items.some(x=>x.startsWith('Pedidos: No se pudo completar')));
 h=harness([registration('pos',worker('installed','redundant'))]);await h.api.handlePwaApply();assert.equal(h.data.get(h.api.PWA_KEYS.status),h.api.PWA_STATUS.applyError);assert.equal(h.data.has(h.api.PWA_KEYS.lastUpdate),false);
 h=harness([registration('pos',worker()),registration('pedidos',worker())]);await h.api.handlePwaApply();assert.equal(h.data.get(h.api.PWA_KEYS.status),h.api.PWA_STATUS.applied);assert(h.data.has(h.api.PWA_KEYS.lastUpdate));assert.equal(h.applyButton.disabled,true);assert.equal(h.button.disabled,false);assert.equal(h.items.filter(x=>x.includes('abre el módulo')).length,2);assert.equal(h.items.length,11);
 // Same script URL is insufficient: the old active worker cannot confirm the new target.
 const target=worker('redundant'),reg=registration('pos');reg.active.scriptURL=target.scriptURL;assert.equal(await h.api.waitForPwaRegistrationActivation(reg,target,1),false);
 h=harness([],true);await h.api.handlePwaApply();assert.equal(h.data.get(h.api.PWA_KEYS.status),h.api.PWA_STATUS.partialSearch);
 h=harness([registration('pos',worker())],true);h.data.set(h.api.PWA_KEYS.lastUpdate,'histórico');await h.api.handlePwaApply();assert.equal(h.data.get(h.api.PWA_KEYS.status),h.api.PWA_STATUS.partialApply);assert.equal(h.data.get(h.api.PWA_KEYS.lastUpdate),'histórico');assert.equal(h.items.length,11);
 h=harness([],true);await h.api.handlePwaCheck();assert.equal(h.data.get(h.api.PWA_KEYS.status),h.api.PWA_STATUS.noRegistered);assert.equal(h.applyButton.disabled,true);
 h=harness([]);await h.api.handlePwaCheck();assert(h.registered.every(row=>row.url.endsWith('/sw.js')&&row.options.updateViaCache==='none'));assert.equal(h.registered.length,11);await h.api.handlePwaCheck();assert.equal(h.registered.length,11);
 const stuck=registration('pos');stuck.update=()=>new Promise(()=>{});h=harness([stuck]);await h.api.handlePwaCheck();assert.equal(h.data.get(h.api.PWA_KEYS.status),h.api.PWA_STATUS.partialSearch);assert.equal(h.button.disabled,false);
 const failedPending=registration('pos',worker());failedPending.update=async()=>{throw new Error('sin conexión');};h=harness([failedPending,registration('pedidos',worker())]);await h.api.handlePwaApply();assert.equal(h.data.get(h.api.PWA_KEYS.status),h.api.PWA_STATUS.partialApply);assert.equal(failedPending.waiting.state,'installed');assert(h.items.some(row=>row.startsWith('POS: No se pudo completar')));

 h=harness(ids.map(id=>registration(id)));h.data.set(h.api.PWA_KEYS.lastUpdate,'histórico');h.api.pwaRuntime.lastResults=[{id:'pos',label:'POS',status:'available',error:''}];h.data.set(h.api.PWA_KEYS.status,h.api.PWA_STATUS.available);await h.api.reconcilePwaState();assert.equal(h.applyButton.disabled,true);assert.equal(h.data.get(h.api.PWA_KEYS.lastUpdate),'histórico');assert.equal(JSON.parse(h.data.get(h.api.PWA_KEYS.notice)).kind,'unconfirmed');assert.equal(h.registered.length,0);
 const observedReg=registration('pos',worker());h=harness([observedReg,...ids.filter(id=>id!=='pos').map(id=>registration(id))]);h.api.observePwaActivation(observedReg,observedReg.waiting);const activated=observedReg.waiting;observedReg.active=activated;observedReg.waiting=null;activated.postMessage();await new Promise(resolve=>setImmediate(resolve));assert.equal(h.data.get(h.api.PWA_KEYS.status),h.api.PWA_STATUS.automatic);assert(h.data.has(h.api.PWA_KEYS.lastUpdate));const automaticDate=h.data.get(h.api.PWA_KEYS.lastUpdate);await h.api.reconcilePwaState();assert.equal(h.data.get(h.api.PWA_KEYS.lastUpdate),automaticDate);assert.equal(JSON.parse(h.data.get(h.api.PWA_KEYS.notice)).kind,'automatic');
 h.api.pwaRuntime.lastResults=[{id:'pos',label:'POS',status:'available',error:''}];await h.api.reconcilePwaState();assert.equal(JSON.parse(h.data.get(h.api.PWA_KEYS.notice)).kind,'unconfirmed');assert.equal(h.data.get(h.api.PWA_KEYS.lastUpdate),automaticDate);
 h=harness([registration('pos')]);h.data.set(h.api.PWA_KEYS.lastUpdate,'histórico');await h.api.reconcilePwaState();assert.equal(h.data.get(h.api.PWA_KEYS.status),h.api.PWA_STATUS.partialSearch);assert.equal(h.registered.length,0);assert.equal(h.data.get(h.api.PWA_KEYS.lastUpdate),'histórico');
 console.log('PASS: preparación de once módulos, registros ajenos intactos, búsquedas completas/parciales, timeout, activación completa/parcial/fallida, errores conservados y fechas históricas.');
})().catch(e=>{console.error(e);process.exitCode=1;});
