'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { classify, runProcess, inventory } = require('./run-suite.cjs');
(async () => {
  const rows = inventory(JSON.parse(fs.readFileSync(path.join(__dirname, 'catalogo.json'), 'utf8')));
  assert.equal(rows.filter(row => row.aliasOf).length, 3);
  assert.throws(() => inventory({ tests: rows.concat(rows[0]) }), /catálogo/);
  assert.equal(classify({ code: 0, output: 'listen EPERM' }), 'APROBADA');
  assert.equal(classify({ code: 1, output: 'AssertionError: dato inválido' }), 'FALLIDA');
  assert.equal(classify({ code: 1, output: 'TypeError: document.createElement is not a function' }), 'FALLIDA');
  assert.equal(classify({ code: 1, output: 'listen EPERM: operation not permitted 127.0.0.1' }), 'BLOQUEADA_ENTORNO');
  assert.equal(classify({ code: 1, output: "browserType.launch: Executable doesn't exist at /tmp/chrome" }), 'BLOQUEADA_ENTORNO');
  assert.equal(classify({ code: 1, output: 'AssertionError', timedOut: true }), 'INCONCLUSA');
  assert.equal((await runProcess(['-e', "console.log('ok')"], 2000)).status, 'APROBADA');
  assert.equal((await runProcess(['-e', 'process.exit(3)'], 2000)).status, 'FALLIDA');
  const hung = await runProcess(['-e', 'setInterval(()=>{},1000)'], 100);
  assert.equal(hung.status, 'INCONCLUSA');
  assert.equal(hung.timedOut, true);
  const large = await runProcess(['-e', "process.stdout.write('x'.repeat(150000))"], 2000);
  assert.equal(large.truncated, true);
  assert.equal(large.output.length, 131072);
  const preserve = await runProcess([path.join(__dirname, 'run-suite.cjs'), '--report', path.join(__dirname, 'catalogo.json')], 2000);
  assert.equal(preserve.code, 2);
  assert.match(preserve.output, /se conserva sin sobrescribir/);
  const selection = await runProcess([path.join(__dirname, 'run-suite.cjs'), '--test', 'a33-pwa-e1-componentes-vigentes.smoke.cjs', '--test', 'a33-pwa-e1-componentes-vigentes.smoke.cjs'], 2000);
  assert.equal(selection.status, 'APROBADA');
  assert.equal(selection.output.match(/APROBADA a33-pwa-e1/g).length, 1);
  const aliases = await runProcess([path.join(__dirname, 'run-suite.cjs'), '--test', 'a33-pos-efectivo-etapa1-creditos.smoke.cjs', '--test', 'a33-pos-efectivo-etapa2-blindaje.smoke.cjs'], 2000);
  assert.equal(aliases.output.match(/(?:FALLIDA|APROBADA) a33-pos-efectivo/g).length, 1);
  assert(!aliases.output.includes('Prueba desconocida'));
  const publication = await runProcess([path.join(__dirname, 'run-suite.cjs'), '--group', 'publicacion'], 3000);
  assert.equal(publication.status, 'APROBADA');
  assert.equal(publication.output.match(/APROBADA a33-/g).length, 1);
  assert.match(publication.output, /a33-publicacion-coherencia/);
  const invalidGroup = await runProcess([path.join(__dirname, 'run-suite.cjs'), '--group', 'desconocido'], 2000);
  assert.equal(invalidGroup.code, 2);
  assert.match(invalidGroup.output, /Grupo desconocido/);
  console.log('PASS: catálogo, aliases, errores funcionales, bloqueos explícitos, procesos aislados y timeout sin falso aprobado.');
})().catch(error => { console.error(error); process.exitCode = 1; });
